services:
  tldraw:
    image: bradmartin333/node-tldraw:latest
    container_name: tldraw
    restart: always
    ports:
      - 3000:3000
    volumes:
      - tldraw_sync_data:/data
    # Custom logos (See README.md for details)
    # configs:
    #   - source: logo_light
    #     target: /app/dist/assets/light.webp
    #   - source: logo_dark
    #     target: /app/dist/assets/dark.webp

volumes:
  tldraw_sync_data:

# Custom logos (See README.md for details)
# configs:
#   logo_light:
#     file: ./logo-light.webp
#   logo_dark:
#     file: ./logo-dark.webp
